# Generated by Django 4.1.1 on 2022-09-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModelContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UKCL', models.CharField(db_index=True, default='-', max_length=2000)),
                ('prev_UKCL', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('name', models.CharField(max_length=500)),
                ('dataset_I_belong_to',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='ks.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
